services:
  notifications-api:
    image: notifications-api:1.0.0
    container_name: notifications-api
    build: notificationsapi
    command: npm run dev
    volumes:
      - ./notificationsapi/src:/app/src
    ports:
      - "3000:3000"
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    command: postgres
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: dbadminpass
      PGUSER: "dbadmin"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  app: 
    image: node:lts
    container_name: notificationsapp
    build: notificationsapp
    ports:
      - "8080:8080"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./notificationsapp/src:/app/src:cached
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
    - CHOKIDAR_INTERVAL=1000
volumes:
  db:
    driver: local
