services:
  notifications-api:
    image: notifications-api:1.0.0
    container_name: notifications-api
    build: notificationsapi
    command: npm run dev
    volumes:
      - ./notificationsapi/src:/app/src
    ports:
      - "3000:3000"
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    command: postgres
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: dbadminpass
      PGUSER: "dbadmin"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
