<script>
export default {
  data: () => {
    return {
      id: this.$router.params.id,
      user: {},
    };
  },
  async onBeforeMount() {
    console.log(this)
    await fetch(`http://localhost:3000/user/${id}`)
      .then((res) => res.json())
      .then((data) => {
        Object.keys(data).forEach((prop) => {
          user[prop] = data[prop];
        });
        return data;
      });
  },

  methods: {
    goHome() {
      useRouter("/");
    },
  },
};
import { onBeforeMount, reactive, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import router from "../router/index.js";
</script>

<template>
  <v-btn @click="goHome">Go Home</v-btn>
  <Router-Link to="/" class="link">Go home</Router-Link>
  <div v-if="user.first_name">
    <h1>This is {{ user.first_name }}´s dashboard</h1>
    <h2>{{ user.first_name }}´s email is: {{ user.email }}</h2>
    <h2>These are your notifications:</h2>
    <h4 v-for="notification in user.mynotifications">
      {{ notification.notification_type }}
    </h4>
    <h2>These are notifications generated by you:</h2>
    <h4 v-for="notification in user.mygeneratednotifications">
      {{ notification.notification_type }}
    </h4>
  </div>
  <h1 v-else>loading data...</h1>
</template>

<style>
link {
  font-size: 10rem;
  color: aqua;
}
</style>
