<template>
  <v-card>
    <v-row no-gutters>
      <v-col xs="{8}">
        <div v-if="this.user.first_name" :key="this.user.appuserid">
          <h1>This is {{ this.user.first_name }}´s dashboard</h1>
          <h2>{{ this.user.first_name }}´s email is: {{ user.email }}</h2>
          <h2>These are your notifications:</h2>
          <NotificationsTable
            :usernotifications="user.mygeneratednotifications"
            :users="users"
            :headers="headers"
            @select="$emit('select', {})"
          />
          <h2>These are notifications generated by you:</h2>
          <NotificationsTable
            :usernotifications="user.mynotifications"
            :users="users"
            :headers="headers"
            @select="$emit('select', {})"
          />
        </div>
        <h1 v-else>loading data...</h1></v-col
      >
      <v-col xs="{4}">
        <h1>User actions</h1>
        <v-select v-model="selectAction" :items="actions"> </v-select>
        <v-select v-model="selectTargetUser" :items="userNames"> </v-select>
        <v-btn @click="createNotification">Create notification</v-btn>
      </v-col>
    </v-row>
    <v-btn @click="$emit('select', {})">Go back</v-btn>
  </v-card>
</template>

<script>
import NotificationsTable from "./NotificationsTable.vue";
export default {
  name: "UserDashboard",
  props: ["userid", "users"],
  data: () => ({
    user: {},
    selectAction: "",
    selectTargetUser: "",
    headers: [
      { text: "read", value: "read" },
      { text: "notification_type", value: "notification_type" },
    ],
    actions: [
      "obtained a grant for the team!",
      "completed compliance procedures!",
      "sent some courses!",
      "created a new story!",
      "generated an initiative!",
    ],
  }),
  computed: {
    userNames() {
      console.log("here");
      let userNames = this.users
        .filter((elem) => elem.appuserid !== this.user.appuserid)
        .map((elem) => {
          console.log(elem);
          return `${elem.first_name} ${elem.last_name}`;
        });
      return userNames;
    },
  },
  async beforeMount() {
    console.log(this.users);
    this.user = await fetch(`http://localhost:3000/user/${this.userid}`)
      .then((res) => res.json())
      .then((res) => {
        return res;
      });
  },
  methods: {
    async createNotification() {
      const targetId = this.getTargetId();
      await fetch(`http://localhost:3000/notification/`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          actorid: this.user.appuserid,
          notifierid: targetId,
          notification_type: this.selectAction,
        }),
      })
        .then((res) => res.json())
        .then((data) => {
          console.log(data);
        });
    },
    getTargetId() {
      const foundTargetUser = this.users.find(
        (elem) =>
          `${elem.first_name} ${elem.last_name}` === this.selectTargetUser
      );
      console.log("found", foundTargetUser);
      return foundTargetUser.appuserid;
    },
  },
  components: { NotificationsTable },
};
</script>
